name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

env:
  # Secrets are configured on github.com in repository settings
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    name: Build & deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pipenv

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --ignore-pipfile --dev

      - name: Build html
        run: pipenv run html_gen

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        working-directory: html
        run:
          vercel pull --yes --environment=production --token=${{
          secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: html
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: html
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
